name: Build and publish to PyPi

on:
  push:
    tags:
      - '*'

jobs:
  build-n-publish:
    name: Build and publish to PyPi
    runs-on: ubuntu-latest

steps:
  - uses: actions/checkout@master
  - name: Set up Python 3.10
    uses: actions/setup-python@v2
    with:
      python-version: 3.10
  - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install poetry
      poetry install -v
  - name: Build with poetry
    run: |
      poetry publish --build
  - name: Publish to PyPi
    uses: pypa/gh-action-pypi-publish@master
    with:
      password: ${{ secrets.PYPI_API_TOKEN }}
